/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BeforeAll: typeof import('./components/help/before-all.vue')['default']
    InputAnkiConnectUrl: typeof import('./components/input-anki-connect-url.vue')['default']
    OpenAnkiConnectCard: typeof import('./components/help/open-anki-connect-card.vue')['default']
    OpmlConfigs: typeof import('./components/mubu-opml/opml-configs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
